name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Allow the workflow to write the Pages site
permissions:
  contents: read
  pages: write
  id-token: write

# Prevent multiple concurrent deploys from stepping on each other
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    # Make the secret available during the build step (ephemeral on the runner)
    env:
      REACT_APP_NASA_API_KEY: ${{ secrets.NASA_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      # Optional: create a .env.production file so CRA will definitely pick up the variable.
      # This file only exists on the runner (not committed to the repo).
      - name: Create .env.production (CRA-friendly)
        run: |
          echo "REACT_APP_NASA_API_KEY=${{ secrets.NASA_API_KEY }}" > .env.production
          echo ".env.production created (for build only)"

      - name: Build site
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    # Note: environment.url can reference the deployment step output.
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4